"""Pydantic data models for ensuring data validation and type safety in the RAG system."""
from pydantic import BaseModel, Field
import uuid


class MinimalSource(BaseModel):
    """Model representing a minimal source of information to identify the location and origin of retrieved documents.

    Attributes:
        file_path (str): Relative file path of the source code or document.
        first_character_index (int): Starting character index of the corresponding text in the original file.
        last_character_index (int): Ending character index of the corresponding text in the original file.
    """
    file_path: str
    first_character_index: int
    last_character_index: int


class UnansweredQuestion(BaseModel):
    """Model representing a single unanswered question included in the dataset.

    Attributes:
        question_id (str): Unique identifier for the question. Auto-generated via UUID if not provided.
        question (str): The text of the question input by the user or provided by the test data.
    """
    question_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    question: str


class AnsweredQuestion(UnansweredQuestion):
    """Model linking a question with its referenced information sources and the answer generated by the LLM.

    Attributes:
        sources (list[MinimalSource]): List of information sources referenced by the RAG system to derive the answer.
        answer (str): The final answer text generated by the LLM (e.g., Qwen model) for the user.
    """
    sources: list[MinimalSource]
    answer: str


class RagDataset(BaseModel):
    """Collection model representing the entire input dataset containing multiple questions (answered or unanswered).

    Attributes:
        rag_questions (list[AnsweredQuestion | UnansweredQuestion]): List of question objects to be processed.
    """
    rag_questions: list[AnsweredQuestion | UnansweredQuestion]


class MinimalSearchResults(BaseModel):
    """Intermediate data model holding the search results (list of sources) for a single question.

    Attributes:
        question_id (str): Unique identifier of the target question.
        question_str (str): The query string of the target question.
        retrieved_sources (list[MinimalSource]): List of top information sources discovered
            by the retriever (e.g., BM25).
    """
    question_id: str
    question_str: str
    retrieved_sources: list[MinimalSource]


class MinimalAnswer(MinimalSearchResults):
    """Search result model including the final generated answer in addition to the retrieved sources.

    Attributes:
        answer (str): The final answer text generated based on the referenced information sources.
    """
    answer: str


class StudentSearchResults(BaseModel):
    """Top-level model for submitting batch search results to the automated grading system (Moulinette).

    Attributes:
        search_results (list[MinimalSearchResults]): List of search result objects for each question.
        k (int): The specified number of results requested and retrieved in each search.
    """
    search_results: list[MinimalSearchResults]
    k: int


class StudentSearchResultsAndAnswer(BaseModel):
    """Top-level model for submitting batch answer results to the automated grading system.

    Attributes:
        search_results (list[MinimalAnswer]): List of objects containing both search results
            and answers for each question.
        k (int): The specified number of results requested and retrieved in each search.
    """
    search_results: list[MinimalAnswer]
    k: int
